//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventureWorks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_100 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_1000 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_10000 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_500 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_5000 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;SalesOrderID&quot;:43659,&quot;RevisionNumber&quot;:8,&quot;OrderDate&quot;:&quot;2011-05-31T00:00:00&quot;,&quot;DueDate&quot;:&quot;2011-06-12T00:00:00&quot;,&quot;ShipDate&quot;:&quot;2011-06-07T00:00:00&quot;,&quot;Status&quot;:5,&quot;OnlineOrderFlag&quot;:false,&quot;SalesOrderNumber&quot;:&quot;SO43659&quot;,&quot;PurchaseOrderNumber&quot;:&quot;PO522145787&quot;,&quot;AccountNumber&quot;:&quot;10-4020-000676&quot;,&quot;CustomerID&quot;:29825,&quot;SalesPersonID&quot;:279,&quot;TerritoryID&quot;:5,&quot;BillToAddressID&quot;:985,&quot;ShipToAddressID&quot;:985,&quot;ShipMethodID&quot;:5,&quot;CreditCardID&quot;:16281,&quot;CreditCardApprovalCode&quot;:&quot;105041Vi84182&quot;,&quot;CurrencyRateID&quot;:null,&quot;SubTotal&quot;:20565.6206,&quot;TaxAmt&quot;:1971.51 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SalesOrderHeaderDetail_50000 {
            get {
                return ResourceManager.GetString("SalesOrderHeaderDetail_50000", resourceCulture);
            }
        }
    }
}
